config/routes.rb
Rails.application.routes.draw do
  resources :boards
  root to: "boards#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :height, numericality: { only_integer: true }
  validates :width, numericality: { only_integer: true }
  validates :number_of_mines, numericality: { only_integer: true }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true

  serialize :array
  serialize :blank

  has_many :mines
end

app/models/mine.rb
class Mine < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
require_relative "#{Rails.root}/lib/generate_board"

class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
    # @mines = Mine.paginate(page: params[:page], per_page: 1000).order(height: :asc, width: :asc)
    @mines = @board.mines.order(height: :asc, width: :asc).to_a
    @tile = "\u2B1C ".freeze
    @bomb = "💣 ".freeze
  end

  # GET /boards/new
  def new
    @recent_boards = Board.all.order(created_at: :desc).limit(10)
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        @generator = GenerateBoard.new(width: @board.width, height: @board.height, number_of_mines: @board.number_of_mines, board: @board.id)
        format.html { redirect_to @board, notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.require(:board).permit(:email, :width, :height, :number_of_mines, :name, :array, :blank)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :number_of_mines %>
    <%= form.number_field :number_of_mines %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Generate Board' %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Width</th>
      <th>Height</th>
      <th>Number of mines</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.email %></td>
        <td><%= board.width %></td>
        <td><%= board.height %></td>
        <td><%= board.number_of_mines %></td>
        <td><%= board.name %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>
<ul class="list-group">
<% @recent_boards.each do |board| %>
  <li class="list-group-item">
    <div class="fw-bold"><%= link_to board.name, board_path(board) %></div>
    <%= board.email %><br />
    <%= board.created_at %><br />
  </li>
<% end %>
</ul>

<%= link_to 'View all generated boards', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Email:</strong>
<%= @board.email %>
</p>

<p>
<strong>Width:</strong>
<%= @board.width %>
</p>

<p>
<strong>Height:</strong>
<%= @board.height %>
</p>

<p>
<strong>Number of mines:</strong>
<%= @board.number_of_mines %>
</p>

<p>
<strong>Name:</strong>
<%= @board.name %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>
<p />
<% cell = 0 %>
<% final_cell = (@board.width * @board.height)%>
<% width = 0 %>
<% @mines.each do |mine| %>

  <% mine = (@board.width * mine.height) + mine.width %>

  <% while cell < mine do %>
    <%= @tile %>
    <% cell += 1 %>

    <% if width == @board.width - 1 %>
      <% width = 0 %>
      <br />
    <% else %>
      <% width += 1 %>
    <% end %>
  <% end %>


  <%= @bomb %>

  <% if width == @board.width - 1 %>
    <% width = 0 %>
    <br />
  <% else %>
    <% width += 1 %>
  <% end %>

  <% cell += 1 %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>